version: "3.9"
services:
  svlyss-winners-api:
    build: ./api
    container_name: svlyss-winners-api
    networks:
      - svlyss
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - data:/python-docker
  svlyss-winners-ui:
    build: ./
    container_name: svlyss-winners-ui
    depends_on:
      - svlyss-winners-api
    networks:
      - svlyss
    restart: always
    ports:
      - "80:80"
    volumes:
      - /etc/letsencrypt/live/svl.kruettlip.ch:/etc/nginx/certs
networks:
  svlyss: {}
volumes:
  data:
